<?php

namespace AppBundle\Repository;

/**
 * AffectationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *  Liste des affectations selon la formation
     * @uses by AffectationController:newAction()
     */
    public function findByFormation($formation)
    {
        return $this->createQueryBuilder('a')
                    ->innerJoin('a.formation', 'f')
                    ->where('f.code = :formation')
                    ->setParameter('formation', $formation)
                    ->getQuery()->getResult()
            ;
    }
}
