<?php

namespace AppBundle\Repository;

/**
 * CertificatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des certificats par ordre decroissant
     * Utiliser dans CertificatController::indexAction()
     */
    public function findListDesc()
    {
        return $this->createQueryBuilder('c')->orderBy('c.code', 'DESC')->getQuery()->getResult();
    }

    /**
     * Liste des certificats disponibles
     * en fonction du type de formation
     * @uses by AffectationController:newAction()
     */
    public function findDisponible($formation)
    {
        return $this->createQueryBuilder('c')
                    ->innerJoin('c.formation', 'f')
                    ->where('f.code = :formation')
                    ->andWhere('c.flag = 0')
                    ->setParameter('formation', $formation)
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Nombre de certificats en fonction de la formation
     * @uses by DefaultController:indexAction()
     */
    public function findNombre($formation, $flag, $region = null)
    {
        if (!$region){
            return $this->createQueryBuilder('c')
                        ->select('count(c.id)')
                        ->innerJoin('c.formation', 'f')
                        ->where('f.code = :formation')
                        ->andWhere('c.flag = :flag')
                        ->setParameters([
                            'formation' => $formation,
                            'flag' =>  $flag
                        ])
                        ->getQuery()->getSingleScalarResult()
                ;
        } else{
            return $this->createQueryBuilder('c')
                ->select('count(c.id)')
                ->innerJoin('c.formation', 'f')
                ->where('f.code = :formation')
                ->andWhere('c.flag = :flag')
                ->andWhere('c.region = :region')
                ->setParameters([
                    'formation'=> $formation,
                    'flag' => $flag,
                    'region' => $region
                ])
                ->getQuery()->getSingleScalarResult()
                ;
        }
    }
}
