<?php

namespace AppBundle\Repository;

/**
 * ChefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChefRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste ordonnée des chefs
     * @uses by ChefController:newAction()
     */
    public function findListeOrd()
    {
        return $this->createQueryBuilder('c')
                    ->orderBy('c.nom', 'ASC')
                    ->addOrderBy('c.prenoms', 'ASC')
                    ->getQuery()->getResult()
            ;
    }
}
