<?php

namespace AppBundle\Repository;

use AppBundle\Form\ParticiperType;

/**
 * ChefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChefRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste ordonnée des chefs
     * @uses by ChefController:newAction()
     */
    public function findListeOrd()
    {
        return $this->createQueryBuilder('c')
                    ->orderBy('c.nom', 'ASC')
                    ->addOrderBy('c.prenoms', 'ASC')
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Liste des stagiaires
     * @uses ParticiperType
     */
    public function listeStagiares($region, $level)
    {
        if ($level == 'C'){
            return $this->createQueryBuilder('c')
                        ->innerJoin('c.region', 'r')
                        ->where('r.id = :region')
                        ->andWhere('c.classe is NULL')
                        ->orderBy('c.nom', 'ASC')
                        ->addOrderBy('c.prenoms', 'ASC')
                        ->setParameter('region', $region)
                ;
        }elseif ($level == 'B'){
            return $this->createQueryBuilder('c')
                        ->innerJoin('c.region', 'r')
                        ->where('r.id = :region')
                        ->andWhere('c.classe <> :A')
                        ->andWhere('c.classe <> :B')
                        ->orderBy('c.nom', 'ASC')
                        ->addOrderBy('c.prenoms', 'ASC')
                        ->setParameters([
                            'region'=> $region,
                            'A'=> 'A',
                            'B'=> 'B'
                        ])
                ;
        }else{
            return $this->createQueryBuilder('c')
                        //->innerJoin('c.region', 'r')
                        //->where('r.id = :region')
                        ->where('c.classe <> :A')
                        ->orderBy('c.nom', 'ASC')
                        ->addOrderBy('c.prenoms', 'ASC')
                        ->setParameters([
                            //'region'=> $region,
                            'A'=> 'A',
                        ])
                ;
        }
    }
}
