<?php

namespace AppBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste ordonnée des regions
     */
    public function liste()
    {
        return $this->createQueryBuilder('r')->where('r.statut = 1')->orderBy('r.libelle', 'ASC');
    }
}
