<?php

namespace AppBundle\Repository;

/**
 * TitularisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitularisationRepository extends \Doctrine\ORM\EntityRepository
{
}
