<?php

namespace AppBundle\Repository;

/**
 * TypeFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeFormationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des formations
     */
    public function liste()
    {
        return $this->createQueryBuilder('tf')->where('tf.statut = 1');
    }
}
